name: tests
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [ powershell, pwsh ]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: my_bucket

      - name: Checkout scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core

      - name: Init tests
        uses: potatoqualitee/psmodulecache@main
        with:
          modules-to-cache: BuildHelpers, Pester
          shell: ${{ matrix.shell }}

      - name: Run tests
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
